### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by lethal233** [sparkcyf/SUSTech_Class_Schedule_to_ics_Conventor#1]
In the 19th line of the main.py
```python

with open('data.json') as f:
```
I change it to 
```python

with open('data.json',encoding='utf-8') as f:
```
otherwise it will cause error:
```shell
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 386: illegal multibyte sequence
```

**Comment by sparkcyf** [comment]
Fixed in https://github.com/sparkcyf/SUSTech_Class_Schedule_to_ics_Conventor/commit/8f94786ac84607a88f6bd1d7d7799a9e6a75515e, thanks!
